const INCREASE_LOADING = 'INCREASE_LOADING'
const DECREASE_LOADING = 'DECREASE_LOADING'
const GET_COMPANIES = 'GET_COMPANIES'
const GET_COMPANIES_FORM = 'GET_COMPANIES_FORM'
const SET_OFFER_DETAIL = 'SET_OFFER_DETAIL'

export {
  INCREASE_LOADING,
  DECREASE_LOADING,
  GET_COMPANIES,
  GET_COMPANIES_FORM,
  SET_OFFER_DETAIL,
}
